### ISSUE TITLE
FALTA

### ISSUE THREAD

**Issue by GustavoBoaz** [GuilhermeCarluz/turma37gen#1]
- [ ] Camada de Usuario
- [ ] Security
- [ ] Swagger
- [ ] Deploy

Siga o exemplo do Blog pessoal abaixo
[https://github.com/conteudoGeneration/blog-pessoal](url)

**Comment by GuilhermeCarluz** [comment]
Boa tarde, Boaz! Eu tinha esquecido de commitar a pasta do blogPessoal.
Acabei de commitar como "Issue #1", só dá uma olhada.

Guilherme, T37 REC.

Em sáb., 20 de nov. de 2021 às 10:42, Gustavo Boaz ***@***.***>
escreveu:
